const item = [
  {
    id: 1,
    img: "https://koike-ya.vn/img/1.b1008ef8.webp",
    firstName: "Snack khoai tây",
    lastName: "Strong Tokyo BBQ",
    fullName: "SNACK KARAMUCHO KHOAI TÂY STRONG LÁT DÀY VỊ THỊT NƯỚNG TOKYO",
    description:
      "Lát cắt khoai tây dày hơn, đậm đà hương vị thịt nướng Tokyo, chắc chắn sẽ khiến bạn ăn mãi không ngừng!",
    title: "Snack Karamucho Khoai tây Strong Lát dày",
    taste: "Vị thịt nướng Tokyo (26g) - (44g) - (80gr)",
    energy: "558",
    calories: "315",
    caloriesPercent: "54",
    totalFat: "35.0",
    totalFatPercent: "66",
    saturatedFat: "13.1",
    natri: "383",
    natriPercent: "16%",
    totalCarbohydrate: "54.6",
    carboPercent: "18%",
    sugar: "9.1",
    protein: "6.2",
    ingredient:
      "Khoai tây 59,0 %, dầu thực vật, bột gia vị thịt nướng 6,0 % (đường, maltodextrin, chất điều vị (E621), muối, bột kem béo thực vật, bột tiêu đen, đạm thực vật thủy phân, bột gà, hương gà giống tự nhiên, hương tỏi giống tự nhiên, màu nhân tạo: Caramen nhóm IV (xử lý amoni sulfit) (E150d), hương bò giống tự nhiên, màu tự nhiên: Parika oleoresin (E160c), chất điều chỉnh độ axit (E330), chất tạo ngọt nhân tạo: Aspartam (E951)).",
    price: 100.0,
    quantity: 10,
  },
  {
    id: 2,
    img: "https://koike-ya.vn/img/2.b8792e5b.webp",
    firstName: "Snack khoai tây",
    lastName: "STRONG lát dày",
    fullName: "SNACK KARAMUCHO KHOAI TÂY STRONG LÁT DÀY VỊ CAY ĐẶC BIỆT",
    description:
      "Lát cắt khoai tây dày hơn, đậm đà hương vị thịt nướng Tokyo, chắc chắn sẽ khiến bạn ăn mãi không ngừng!",
    title: "Snack Karamucho Khoai tây Strong Lát dày",
    taste: "Vị thịt nướng Tokyo (26g) - (44g) - (80gr)",
    energy: "558",
    calories: "315",
    caloriesPercent: "54",
    totalFat: "35.0",
    totalFatPercent: "66",
    saturatedFat: "13.1",
    natri: "383",
    natriPercent: "16%",
    totalCarbohydrate: "54.6",
    carboPercent: "18%",
    sugar: "9.1",
    protein: "6.2",
    ingredient:
      "Khoai tây 59,0 %, dầu thực vật, bột gia vị thịt nướng 6,0 % (đường, maltodextrin, chất điều vị (E621), muối, bột kem béo thực vật, bột tiêu đen, đạm thực vật thủy phân, bột gà, hương gà giống tự nhiên, hương tỏi giống tự nhiên, màu nhân tạo: Caramen nhóm IV (xử lý amoni sulfit) (E150d), hương bò giống tự nhiên, màu tự nhiên: Parika oleoresin (E160c), chất điều chỉnh độ axit (E330), chất tạo ngọt nhân tạo: Aspartam (E951)).",
    price: 100.0,
    quantity: 10,
  },
];
